#By default the code will try to connect to the serial port if an ip address is not given, however if an IP address is given the code will try to connect to that ip address

  urg_node:
    ros__parameters:
      serial_port: "/dev/ttyACM1"
      user_latency: 0.0
      ip_port: 0
      laser_frame_id: "laser"
#     ip_address: "192.168.88.32"
